### ISSUE TITLE
SMACK throwing "Exception: Unexpected argument type."

### ISSUE THREAD

**Issue by bjohannesmeyer** [michael-emmi/ctverif#3]
I am able to verify the following code using `ctverif --entry-points foo_wrapper foo.c`:

```
#include <stdint.h>
#include "ctverif.h"

void foo(uint32_t x) {
        int a;
        if(x == 3) a = 9*7;
}

void foo_wrapper(uint32_t x) {
        public_in(__SMACK_value(x));
        foo(x);
}
```

If I change `x` to a `uint64_t` it also verifies. However if I change `x` to either a `uint8_t` or a `uint16_t`, SMACK throws the following error:

```
ctverif version 1.0.1
SMACK program verifier version 1.9.1
Unexpected argument type.
UNREACHABLE executed at /root/smack/lib/smack/SmackRep.cpp:403!
0  libLLVM-3.9.so.1 0x00007f429ff94fe8 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 56
1  libLLVM-3.9.so.1 0x00007f429ff9315e llvm::sys::RunSignalHandlers() + 62
2  libLLVM-3.9.so.1 0x00007f429ff932ac
3  libpthread.so.0  0x00007f429f0d4390
4  libc.so.6        0x00007f429e273428 gsignal + 56
5  libc.so.6        0x00007f429e27502a abort + 362
6  libLLVM-3.9.so.1 0x00007f429ff39d0a
7  llvm2bpl         0x00000000004b0097 smack::SmackRep::valueAnnotation(llvm::CallInst const&) + 1959
8  llvm2bpl         0x0000000000506c4d smack::SmackInstGenerator::visitCallInst(llvm::CallInst&) + 861
9  llvm2bpl         0x0000000000489d5d
10 llvm2bpl         0x000000000048950d
11 llvm2bpl         0x00000000004889db
12 llvm2bpl         0x0000000000488462
13 llvm2bpl         0x00000000004883c2
14 llvm2bpl         0x0000000000488362
15 llvm2bpl         0x0000000000484782
16 llvm2bpl         0x0000000000483851 smack::SmackModuleGenerator::generateProgram(llvm::Module&) + 1953
17 llvm2bpl         0x000000000048309d smack::SmackModuleGenerator::runOnModule(llvm::Module&) + 29
18 libLLVM-3.9.so.1 0x00007f42a004f6df llvm::legacy::PassManagerImpl::run(llvm::Module&) + 783
19 llvm2bpl         0x0000000000475ebd main + 3069
20 libc.so.6        0x00007f429e25e830 __libc_start_main + 240
21 llvm2bpl         0x0000000000474299 _start + 41
Stack dump:
0.      Program arguments: llvm2bpl /root/verifs/other/b-30K4s2.bc -bpl /root/verifs/other/a-r3cX7Z.bpl -warnings -source-loc-syms -entry-points foo_wrapper -mem-mod-impls 
1.      Running pass 'SMACK generator pass' on module '/root/verifs/other/b-30K4s2.bc'.
Traceback (most recent call last):
  File "/usr/local/bin/smack", line 13, in <module>
    smack.top.main()
  File "/usr/local/bin/../share/smack/top.py", line 585, in main
    frontend(args)
  File "/usr/local/bin/../share/smack/top.py", line 290, in frontend
    return link_bc_files(bitcodes,libs,args)
  File "/usr/local/bin/../share/smack/frontend.py", line 299, in link_bc_files
    llvm_to_bpl(args)
  File "/usr/local/bin/../share/smack/top.py", line 314, in llvm_to_bpl
    try_command(cmd, console=True)
  File "/usr/local/bin/../share/smack/utils.py", line 69, in try_command
    raise Exception(output)
Exception: Unexpected argument type.
UNREACHABLE executed at /root/smack/lib/smack/SmackRep.cpp:403!
0  libLLVM-3.9.so.1 0x00007f429ff94fe8 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 56
1  libLLVM-3.9.so.1 0x00007f429ff9315e llvm::sys::RunSignalHandlers() + 62
2  libLLVM-3.9.so.1 0x00007f429ff932ac
3  libpthread.so.0  0x00007f429f0d4390
4  libc.so.6        0x00007f429e273428 gsignal + 56
5  libc.so.6        0x00007f429e27502a abort + 362
6  libLLVM-3.9.so.1 0x00007f429ff39d0a
7  llvm2bpl         0x00000000004b0097 smack::SmackRep::valueAnnotation(llvm::CallInst const&) + 1959
8  llvm2bpl         0x0000000000506c4d smack::SmackInstGenerator::visitCallInst(llvm::CallInst&) + 861
9  llvm2bpl         0x0000000000489d5d
10 llvm2bpl         0x000000000048950d
11 llvm2bpl         0x00000000004889db
12 llvm2bpl         0x0000000000488462
13 llvm2bpl         0x00000000004883c2
14 llvm2bpl         0x0000000000488362
15 llvm2bpl         0x0000000000484782
16 llvm2bpl         0x0000000000483851 smack::SmackModuleGenerator::generateProgram(llvm::Module&) + 1953
17 llvm2bpl         0x000000000048309d smack::SmackModuleGenerator::runOnModule(llvm::Module&) + 29
18 libLLVM-3.9.so.1 0x00007f42a004f6df llvm::legacy::PassManagerImpl::run(llvm::Module&) + 783
19 llvm2bpl         0x0000000000475ebd main + 3069
20 libc.so.6        0x00007f429e25e830 __libc_start_main + 240
21 llvm2bpl         0x0000000000474299 _start + 41
Stack dump:
0.      Program arguments: llvm2bpl /root/verifs/other/b-30K4s2.bc -bpl /root/verifs/other/a-r3cX7Z.bpl -warnings -source-loc-syms -entry-points foo_wrapper -mem-mod-impls 
1.      Running pass 'SMACK generator pass' on module '/root/verifs/other/b-30K4s2.bc'.
```

FWIW I'm using Ctverif version 1.0.1, SMACK version 1.9.1 (specifically the [most recent commit on the develop branch](https://github.com/smackers/smack/commit/b135323a5af67c7daa29b4c232acd7281e23b77e)), and Bam version 1.0.7.

Any idea why this is happening? (Or would this be a better question for the SMACK folks? I'm not quite sure what I'd ask there.) Thanks.

**Comment by bjohannesmeyer** [comment]
Yep, casting it in the wrapper serves as a workaround. Thanks!
