### ISSUE TITLE
Unhandled Error Event

### ISSUE THREAD

**Issue by AlexAmad** [michael-emmi/ctverif#5]
Hey! I have tried to install ctverif on several machines (Linux and WSL) but I always get the same error when I run ctverif on different .c files:

ctverif version 1.0.1
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn smack ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by michael-emmi** [comment]
Hi @AlexAmad the “ENOENT” error suggests that Smack is not installed, or not in your path; see README.md

**Comment by AlexAmad** [comment]
Thanks, it is working now!
